### ISSUE TITLE
Useless required arguments

### ISSUE THREAD

**Issue by vankovp** [Kucoin/kucoin-universal-sdk#3]
Hi. I've just started to learn the Python SDK and the very first attempt reveals very strange behavior: I tried to call get_all_symbols method without argument, assuming there should not be any, but it returned an error: request is required. I had no idea how to construct a proper request and tried to pass just None, and surprisingly the method returned desired data. Could you please take a look at this? This is very confusing. Please see a screenshot attached, client initialization was taken from READMI example.

![image](https://github.com/user-attachments/assets/5e2c0889-3a88-458b-9d0d-41b8a7f4d3c1)

**Comment by ISAAC-XXYYZZ** [comment]
This interface requires parameters. For detailed documentation, please refer to: [KuCoin API Documentation](https://www.kucoin.com/docs-new/3470154e0).

Example:

```python
builder = GetAllSymbolsReqBuilder()
builder.set_market("USDS")
req = builder.build()
try:
    resp = self.api.get_all_symbols(req)
    print("code: ", resp.common_response.code)
    print("msg: ", resp.common_response.message)
    print("data: ", resp.to_json())
except Exception as e:
    print("error: ", e)
    raise e

```
